#!/usr/bin/env python3

# counters:${t.category}:${t.aspect}:${t.severity}:${t.name}:value
# counters:${t.category}:${t.aspect}:${t.severity}:${t.name}:rate

import sys
import json

from xml.etree import ElementTree 


HEADER = """// Automatically generated by generate-counters.py

export interface CounterGlobal {
    name?: string;
    category?: string;
    aspect?: string;
    severity?: string;
    desc?: string;
}

export const CounterGlobalList: CounterGlobal[] = ["""


FOOTER = """];
"""


def main():
    et = ElementTree.parse(sys.argv[1])
    root = et.getroot()

    print("// From {}".format(sys.argv[1]))
    print(HEADER)

    entries = []
    for entry in root.findall('.//entry'):
        translated_entry = {}

        for attr in entry:
            if attr.tag not in ["name", "category", "aspect", "severity", "desc"]:
                continue

            desc = ""
            if attr.text:
                desc = attr.text
            translated_entry[attr.tag] = desc.strip()

        entries.append(translated_entry)

    for e in sorted(entries, key=lambda e: e["name"]):
        print(json.dumps(e, indent=4)+',')

    print(FOOTER)


if __name__ == "__main__":
    main()

#        print('    {{name: "counters:{category}:{aspect}:{severity}:{name}:value", description: "Counters: {desc}"}},'.format(**translated_entry))
#        print('    {{name: "counters:{category}:{aspect}:{severity}:{name}:rate", description: "Counters: {desc}"}},'.format(**translated_entry))
